### ISSUE TITLE
有時候已購買的特效會消失

### ISSUE THREAD

**Issue by GoodestEnglish** [MC-Naluwan/Naluwan-Issues#17]
![image](https://user-images.githubusercontent.com/45838505/120419733-0040e980-c331-11eb-8100-59bfdf975ad7.png)
很久以前購買了紅石擊殺特效, 結果回來發現不見了

**Comment by RealGoodestEnglish** [comment]
IGN: GoodestEnglish

**Comment by lulu2002** [comment]
目前看到玩家特效幾乎沒有消失，只有錢消失的問題

能否請你提供任何證據證明特效確實消失了呢？感謝

**Comment by RealGoodestEnglish** [comment]
https://youtu.be/v9NXC6vWahk
1:10:57 這場戰鬥有顯示擊殺特效
￼
￼8月10日，同樣的￼事情￼￼發生在我身上
￼￼￼該次問題已有回報在那魯灣discord，魯魯也有把擊殺特效還給我
這件事應該有關聯，特意說明一下￼￼￼ ￼￼
